site_name: Seer - A Windows Quick Look Tool
nav:
  - Home: index.md
  - 添加插件: 1.-如何添加插件.md
  - 使用控制栏启动程序: 2.-如何使用控制栏启动程序.md
  - 制作一款插件: 3.-制作一款插件.md
  - 第三方程序的兼容问题: 4.-第三方程序的兼容问题.md
  - 自定义配置文件: 5.-自定义配置文件-user.ini.md
  - 激活相关问题: 6.-激活相关问题.md
  - 脚本功能: 7.-如何使用脚本功能.md
  - 自定义配置文件路径: 8.-自定义配置文件路径.md
  - 杂项: 9.-杂项.md
  - 更新日志:
      - Index: changelog/index.md
      - 4.0.2: changelog/4.0.2.md
      - 4.0.1: changelog/4.0.1.md
      - 4.0.0: changelog/4.0.0.md
theme:
  name: material
  hide:
    - versions
  features:
    - toc.integrate
  palette:
    scheme: slate
    primary: blue
    accent: light blue
